accent = "#A00000"
cursor = "#B91C1C"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

color0 = "#333333"
color1 = "#A00000"
color2 = "#FF0000"
color3 = "#A00000"
color4 = "#ff8181"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FF0000"
color11 = "#A00000"
color12 = "#ff8181"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
